"use client";

import {
  Activity,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  Archive,
  ArrowLeft,
  ArrowRight,
  ArrowUpCircle,
  ArrowUpRight,
  AtSign,
  BarChart3,
  Bell,
  BookOpen,
  Bookmark,
  BrainCircuit,
  Calendar,
  CalendarClock,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  ClipboardList,
  Clock,
  Code2,
  Cpu,
  Database,
  Download,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Folder,
  Github,
  Globe,
  GraduationCap,
  HeartHandshake,
  History,
  Home,
  Info,
  Instagram,
  Key,
  Languages,
  Layers,
  LayoutDashboard,
  LifeBuoy,
  Linkedin,
  Loader,
  Lock,
  MapPin,
  LogIn,
  LogOut,
  Mail,
  MailCheck,
  Menu,
  Minus,
  Moon,
  MoreHorizontal,
  MousePointerClick,
  Paperclip,
  Play,
  PlayCircle,
  Plus,
  RefreshCw,
  RotateCcw,
  Save,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  ShieldOff,
  Smartphone,
  Sparkles,
  Star,
  Sun,
  Target,
  Terminal,
  TrendingUp,
  Trash2,
  Twitter,
  Upload,
  UploadCloud,
  User,
  UserCheck,
  UserPlus,
  UserX,
  Users,
  Video,
  X,
  XCircle,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  "alert-circle": AlertCircle,
  "alert-octagon": AlertOctagon,
  "alert-triangle": AlertTriangle,
  archive: Archive,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up-circle": ArrowUpCircle,
  "arrow-up-right": ArrowUpRight,
  "at-sign": AtSign,
  "bar-chart-3": BarChart3,
  bell: Bell,
  "book-open": BookOpen,
  bookmark: Bookmark,
  "brain-circuit": BrainCircuit,
  calendar: Calendar,
  "calendar-clock": CalendarClock,
  check: Check,
  "check-circle": CheckCircle,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  circle: Circle,
  "clipboard-list": ClipboardList,
  clock: Clock,
  "code-2": Code2,
  compass: Target,
  cpu: Cpu,
  database: Database,
  download: Download,
  "edit-3": Edit3,
  "external-link": ExternalLink,
  eye: Eye,
  "eye-off": EyeOff,
  "file-text": FileText,
  filter: Filter,
  folder: Folder,
  github: Github,
  globe: Globe,
  "graduation-cap": GraduationCap,
  "heart-handshake": HeartHandshake,
  history: History,
  home: Home,
  info: Info,
  instagram: Instagram,
  key: Key,
  languages: Languages,
  layers: Layers,
  "layout-dashboard": LayoutDashboard,
  "life-buoy": LifeBuoy,
  linkedin: Linkedin,
  loader: Loader,
  lock: Lock,
  "map-pin": MapPin,
  "log-in": LogIn,
  "log-out": LogOut,
  mail: Mail,
  "mail-check": MailCheck,
  menu: Menu,
  minus: Minus,
  moon: Moon,
  "more-horizontal": MoreHorizontal,
  "mouse-pointer-click": MousePointerClick,
  paperclip: Paperclip,
  play: Play,
  "play-circle": PlayCircle,
  plus: Plus,
  "refresh-cw": RefreshCw,
  "rotate-ccw": RotateCcw,
  save: Save,
  search: Search,
  send: Send,
  settings: Settings,
  "share-2": Share2,
  shield: Shield,
  "shield-check": ShieldCheck,
  "shield-off": ShieldOff,
  smartphone: Smartphone,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  target: Target,
  terminal: Terminal,
  "trending-up": TrendingUp,
  "trash-2": Trash2,
  twitter: Twitter,
  upload: Upload,
  "upload-cloud": UploadCloud,
  user: User,
  "user-check": UserCheck,
  "user-plus": UserPlus,
  "user-x": UserX,
  users: Users,
  video: Video,
  x: X,
  "x-circle": XCircle,
};

export type IconName = keyof typeof ICONS;

export interface IconProps {
  name: string;
  size?: number;
  strokeWidth?: number;
  className?: string;
  style?: React.CSSProperties;
}

export function Icon({ name, size = 18, strokeWidth = 1.75, className, style }: IconProps) {
  const Component = ICONS[name];
  if (!Component) return null;
  return <Component size={size} strokeWidth={strokeWidth} className={className} style={style} />;
}
